namespace ALAN.Shared.Models;

/// <summary>
/// Represents a code change proposal generated by the agent.
/// </summary>
public class CodeProposal
{
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public DateTime Created { get; set; } = DateTime.UtcNow;
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Reasoning { get; set; } = string.Empty;
    public List<FileChange> FileChanges { get; set; } = new();
    public ProposalStatus Status { get; set; } = ProposalStatus.Pending;
    public string? ApprovedBy { get; set; }
    public DateTime? ApprovedAt { get; set; }
    public string? RejectionReason { get; set; }
    public string? BranchName { get; set; }
    public string? PullRequestUrl { get; set; }
}

public class FileChange
{
    public string FilePath { get; set; } = string.Empty;
    public ChangeType Type { get; set; }
    public string? OriginalContent { get; set; }
    public string NewContent { get; set; } = string.Empty;
    public string Diff { get; set; } = string.Empty;
}

public enum ChangeType
{
    Add,
    Modify,
    Delete
}

public enum ProposalStatus
{
    Pending,
    Approved,
    Rejected,
    Implemented,
    Failed
}
